In [1]:
# Face Recognition

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model_2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Nakul'
        if(pred[0][0]>0.5):
            name='Employee'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

<>:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Nakul\AppData\Local\Temp\ipykernel_31412\2711696874.py:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


1/1 [==============================] - 1s 579ms/step
[[9.9957269e-01 4.2733926e-04]]
1/1 [==============================] - 0s 250ms/step
[[0.15187512 0.84812486]]
1/1 [==============================] - 0s 254ms/step
[[9.9960691e-01 3.9317194e-04]]
1/1 [==============================] - 0s 260ms/step
[[0.99899465 0.00100531]]
1/1 [==============================] - 0s 276ms/step
[[0.93009263 0.06990732]]
1/1 [==============================] - 0s 257ms/step
[[0.15033591 0.8496641 ]]
1/1 [==============================] - 0s 242ms/step
[[3.8989861e-06 9.9999607e-01]]
1/1 [==============================] - 0s 240ms/step
[[2.3735269e-07 9.9999976e-01]]
1/1 [==============================] - 0s 234ms/step
[[1.0988479e-09 1.0000000e+00]]
1/1 [==============================] - 0s 232ms/step
[[1.5440712e-05 9.9998450e-01]]
1/1 [==============================] - 0s 234ms/step
[[7.3395645e-06 9.9999261e-01]]
1/1 [==============================] - 0s 231ms/step
[[2.3849023e-18 1.0000000e+00]]
1/1 

1/1 [==============================] - 0s 258ms/step
[[1.1750404e-05 9.9998820e-01]]
1/1 [==============================] - 0s 255ms/step
[[1.14037086e-07 9.99999881e-01]]
1/1 [==============================] - 0s 250ms/step
[[2.0823481e-05 9.9997914e-01]]
1/1 [==============================] - 0s 261ms/step
[[3.5170737e-07 9.9999964e-01]]
1/1 [==============================] - 0s 256ms/step
[[7.0518674e-08 9.9999988e-01]]
1/1 [==============================] - 0s 253ms/step
[[1.82666e-08 1.00000e+00]]
1/1 [==============================] - 0s 255ms/step
[[3.6504155e-09 1.0000000e+00]]
1/1 [==============================] - 0s 252ms/step
[[0.00654259 0.9934574 ]]
1/1 [==============================] - 0s 252ms/step
[[3.9586606e-08 1.0000000e+00]]
1/1 [==============================] - 0s 259ms/step
[[1.612923e-08 1.000000e+00]]
1/1 [==============================] - 0s 251ms/step
[[1.5268873e-11 1.0000000e+00]]
1/1 [==============================] - 0s 268ms/step
[[7.484880e-06 9.99992